import { runPython } from './py.js';
/**
 * docx 原位重排：保留源 docx 的 全部内容（OMML 公式、表格、图片、样式、目录），
 * 只在公式占位符（【待展开】等）位置插入 LaTeX→OMML 公式，按需套用格式档案的标题样式。
 * 绝不做"抽取文本→重建"，避免丢失任何结构。
 */
export async function patchDocxFormulas(projectRoot, workDir, sourcePath, outPath, latexByOccurrence, pythonPath, headingRestyle = false) {
    const code = [
        'import sys, json, re, os, tempfile, zipfile',
        'from docx import Document',
        'from lxml import etree',
        '',
        "M_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/math'",
        'source, out, latex_json, restyle = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4] == "1"',
        'latex_list = json.loads(latex_json)',
        '',
        'def latex_to_omml_mathml(latex, inline):',
        '    # 主转换：latex2mathml → mathml2omml（对 \\\\text、\\\\mathbb 等支持更稳）',
        '    try:',
        '        import latex2mathml.converter as conv',
        '        import mathml2omml',
        '        mathml = conv.convert(latex)',
        '        omml = mathml2omml.convert(mathml)',
        '        if "xmlns:m" not in omml.split(">")[0]:',
        '            omml = omml.replace("<m:oMath>", \'<m:oMath xmlns:m="\' + M_NS + \'">\', 1)',
        '        el = etree.fromstring(omml.encode("utf-8"))',
        '        if not inline:',
        '            # 显示公式：包 m:oMathPara 并居中',
        '            para = etree.fromstring(\'<m:oMathPara xmlns:m="\' + M_NS + \'"><m:oMathParaPr><m:jc m:val="center"/></m:oMathParaPr></m:oMathPara>\')',
        '            para.append(el)',
        '            return para',
        '        return el',
        '    except Exception:',
        '        return None',
        '',
        'def latex_to_omml_pandoc(latex, inline):',
        '    # 备选：pandoc（pypandoc-binary 自带）',
        '    try:',
        '        import pypandoc',
        '        src = ("$" + latex + "$") if inline else ("$$" + latex + "$$")',
        '        tex = "\\\\documentclass{article}\\n\\\\usepackage{amsmath}\\n\\\\begin{document}\\n" + src + "\\n\\\\end{document}"',
        '        d = tempfile.mkdtemp()',
        '        tp = os.path.join(d, "eq.tex")',
        '        open(tp, "w", encoding="utf8").write(tex)',
        '        dp = os.path.join(d, "eq.docx")',
        '        pypandoc.convert_file(tp, "docx", outputfile=dp)',
        '        z = zipfile.ZipFile(dp)',
        '        xml = z.read("word/document.xml").decode("utf8")',
        '        pat = r"<m:oMath>.*?</m:oMath>" if inline else r"<m:oMathPara>.*?</m:oMathPara>"',
        '        m = re.search(pat, xml, re.S)',
        '        if not m: return None',
        '        omml = m.group(0)',
        '        tag_end = omml.find(">")',
        '        if tag_end > 0 and "xmlns:m" not in omml[:tag_end]:',
        '            omml = omml[:tag_end] + \' xmlns:m="\' + M_NS + \'"\' + omml[tag_end:]',
        '        el = etree.fromstring(omml)',
        '        return el',
        '    except Exception:',
        '        return None',
        '',
        'def latex_to_omml(latex, inline):',
        '    el = latex_to_omml_mathml(latex, inline)',
        '    if el is not None:',
        '        return el',
        '    return latex_to_omml_pandoc(latex, inline)',
        '',
        'doc = Document(source)',
        '# 1) 按文档顺序发现括号占位符',
        'bracket_pat = re.compile(r"【([^】]{1,20})】")',
        'markers = []  # [para_idx, start, end, marker]',
        'for pi, p in enumerate(doc.paragraphs):',
        '    for m in bracket_pat.finditer(p.text):',
        '        inner = m.group(1)',
        '        if re.search(r"待展开|待补充|待定|公式|略", inner):',
        '            markers.append([pi, m.start(), m.end(), m.group(0)])',
        '# 2) 行级占位符（推导略 等）',
        'for pi, p in enumerate(doc.paragraphs):',
        '    t = p.text.strip()',
        '    if len(t) <= 40 and re.search(r"(推导|证明|公式).{0,4}(略|从略|略去)", t):',
        '        markers.append([pi, -1, -1, t])',
        '',
        'if len(markers) != len(latex_list):',
        '    print("MARKER_MISMATCH", len(markers), len(latex_list))',
        '    sys.exit(1)',
        '',
        'root = doc.element',
        'if "m" not in root.nsmap:',
        '    root.set("xmlns:m", M_NS)',
        '',
        'inserted = 0',
        'failed = 0',
        'failed_idx = []',
        'for idx, (pi, start, end, marker) in enumerate(markers):',
        '    latex = latex_list[idx]',
        '    if latex is None:',
        '        failed += 1',
        '        failed_idx.append(idx + 1)',
        '        continue  # 该处公式生成失败：保留原占位符不动',
        '    inline = start >= 0',
        '    omml = latex_to_omml(latex, inline)',
        '    if omml is None:',
        '        failed += 1',
        '        failed_idx.append(idx + 1)',
        '        continue  # 该处转换失败：保留原占位符，不中断整篇',
        '    p = doc.paragraphs[pi]',
        '    if start < 0:',
        '        # 行级占位符：整段替换为显示公式',
        '        for r in list(p.runs):',
        '            r._r.getparent().remove(r._r)',
        '        p._p.append(omml)',
        '        inserted += 1',
        '        continue',
        '    runs = p.runs',
        '    pos = 0',
        '    rstart = rend = None',
        '    for ri, r in enumerate(runs):',
        '        rlen = len(r.text)',
        '        if rstart is None and start < pos + rlen:',
        '            rstart = ri',
        '        if pos + rlen >= end:',
        '            rend = ri',
        '            break',
        '        pos += rlen',
        '    if rstart is None:',
        '        failed += 1',
        '        failed_idx.append(idx + 1)',
        '        continue',
        '    # 计算各 run 文本偏移',
        '    pos = 0',
        '    offsets = []',
        '    for r in runs:',
        '        offsets.append((pos, pos + len(r.text)))',
        '        pos += len(r.text)',
        '    s0, e0 = offsets[rstart]',
        '    s1, e1 = offsets[rend]',
        '    prefix = runs[rstart].text[: start - s0]',
        '    suffix = runs[rend].text[end - s1 :] if rend >= 0 else ""',
        '    if rend > rstart:',
        '        runs[rstart].text = prefix',
        '        runs[rend].text = suffix',
        '        for ri in range(rstart + 1, rend):',
        '            runs[ri].text = ""',
        '    else:',
        '        runs[rstart].text = prefix + suffix',
        '    runs[rstart]._r.addnext(omml)',
        '    inserted += 1',
        '',
        'if restyle:',
        '    for p in doc.paragraphs:',
        '        t = p.text.strip()',
        '        try:',
        '            if re.match(r"^第[一二三四五六七八九十百]+章", t) or t in ("摘要", "参考文献"):',
        '                p.style = doc.styles["Heading 1"]',
        '            elif re.match(r"^\\d+\\.\\d+\\s+\\S", t):',
        '                p.style = doc.styles["Heading 2"]',
        '            elif re.match(r"^\\d+\\.\\d+\\.\\d+\\s+\\S", t):',
        '                p.style = doc.styles["Heading 3"]',
        '        except Exception:',
        '            pass',
        '',
        'doc.save(out)',
        'print("DOCX_PATCH_OK", inserted)',
        'if failed:',
        '    print("FORMULA_FAIL", failed, ",".join(str(i) for i in failed_idx))',
        'print("TABLES", len(doc.tables))',
        'zsrc = zipfile.ZipFile(source)',
        'print("MEDIA", len([n for n in zsrc.namelist() if n.startswith("word/media/")]))',
    ].join('\n');
    const res = await runPython(projectRoot, workDir, code, [sourcePath, outPath, JSON.stringify(latexByOccurrence), headingRestyle ? '1' : '0'], 180_000, pythonPath);
    if (!res.ok) {
        return { ok: false, error: res.stderr || res.error || '未知错误' };
    }
    const m = res.stdout.match(/DOCX_PATCH_OK (\d+)/);
    const tables = res.stdout.match(/TABLES (\d+)/);
    const media = res.stdout.match(/MEDIA (\d+)/);
    const fail = res.stdout.match(/FORMULA_FAIL (\d+) ([\d,]+)/);
    if (!m) {
        return { ok: false, error: res.stdout || res.stderr || '未知错误' };
    }
    return {
        ok: true,
        inserted: Number(m[1]),
        tables: tables ? Number(tables[1]) : undefined,
        media: media ? Number(media[1]) : undefined,
        failed: fail ? Number(fail[1]) : 0,
        failedIdx: fail ? fail[2].split(',').map(Number) : [],
    };
}
